import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";

export const metadata:Metadata = {
  title:{
    default:"Next.js Tutorial - Condevolution",
    template:"%s | Condevolution",
    absolute:"",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>   
        <header style={{ backgroundColor: "lightblue", padding: "10px" }}>
          <p>Header</p>
          </header>
          <ErrorWrapper>{children}</ErrorWrapper>
        <footer style={{ backgroundColor: "lightblue", padding: "10px" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
